_core:
  default_config_hash: 0E8z47ONguVcapiw1PGWDRs6g0NRDCzrym4mP_jcELU
auth: {  }
post_login: /user
user_allowed: register
redirect_user_form: false
disable_admin_login: false
disabled_roles: {  }
